Sprint_3
ton-and-polo/scooter_serivce_api pull request #1
Opened 2021-11-24 10:41 UTC by ton-and-polo

Done all project's assignments:
- courier creation
- courier login
- order creation

2021-11-26 11:32 UTC, egorvas requested changes

2021-11-26 11:32 UTC, egorvas commented on src/test/java/yandex/scooter/service/api/CourierLoginTest.java
> +public class CourierLoginTest {
Не вижу теста на логин курьера с неполными данными (без логина/без пароля).

2021-11-26 11:32 UTC, egorvas commented on src/test/java/yandex/scooter/service/api/OrderCreationTest.java
> +            Courier courier = new Courier("mike-courier", "mike123", "Mike");
Думаю что было бы оптимальнее создать одного курьера перед всеми тестами, а потом после всех тестов его удалить. Это не влияет на логику, но тесты станут быстрее.

2021-11-28 14:11 UTC, ton-and-polo commented
Поправил месаджи в тестах (сделал те же, что и в документах). Теперь из-за багов некоторые тесты не проходят)

2021-12-08 07:26 UTC, merged